version: '3.3'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: bb-postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: /start_local.sh
    volumes:
      - .:/app
    container_name: bb-django
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  postgres_data: